### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Sandteufel** [Cheaterdev/starline-ha#1]
Hi! I install your plagin on HASS 0.94.4

and receive errors.
1. if i configure onlu connecntion (login & password without IMEI)
2019-06-25 06:55:08 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/starline/device_tracker.py", line 73, in _update_info
    'ctemp': device['ctemp'],
-----
If I write line with IEMEI of my car and press test configuration I receive errors:
nvalid config for [device_tracker]: expected a dictionary. Got OrderedDict([('default_config', {}), ('http', OrderedDict([('base_url', '192.168.1.11:8123'), ('ssl_certificate', '/ssl/fullchain.pem'), ('ssl_key', '/ssl/privkey.pem'), ('server_host', '0.0.0.0'), ('ssl_profile', 'modern'), ('cors_allowed_origins', []), ('server_port', 8123), ('ip_ban_enabled', True), ('trusted_networks', []), ('login_attempts_threshold', -1)])), ('map', {}), ('conversation', {}), ('group', {}), ('script', {}), ('discovery', {'ignore': [], 'enable': []}), ('hacs', Ordere.... (See /config/configuration.yaml, line 36). Please check the docs at https://home-assistant.io/components/device_tracker/

p.s. Did you see official API from starline? https://developer.starline.ru

**Comment by Cheaterdev** [comment]
Hi. 

First error is definitely a problem, that your device can't report outdoor climate temperature. I'll fix that. 

Issue with checking appeared some months ago when something changed in HA.
Currently i haven't find any solution to pass configuration check, but this integration works without changes. Just ignore that check error. 

About API - this is cool. There was no API year ago when i make this integration and starline support was clearly saying that there will be no API in future. 

I will definitely rewrite this integration with API in future.

Update:
1. For using API starline wants to make contract with them as 3rd app owner if i want to share my app with others. Maybe when is opensource - we don't need to do that. 
2. API has limitation in 1000 calls per day. This is enough for tracking position every 2 mins if there will be no other requests like getting current locks status or temperature.

**Comment by Sandteufel** [comment]
Hi, not working :(

Предлагаю пообщатьмя в телеге, мой ник там @Karntheneros

вт, 25 июн. 2019 г., 12:49 cheater <notifications@github.com>:

**Comment by Cheaterdev** [comment]
Fixed
